### ISSUE TITLE
Multiple players getting mixed up

### ISSUE THREAD

**Issue by cifkao** [magenta/magenta-js#403]
Multiple players on one page don't seem to play well with each other. For example, in the `callback_player` demo, try clicking "play twinkle with click" first and while it is playing, click "play teapot without click". The following happens:

- When the first player stops, the other one stops as well. However, only the callback for the first player gets called.
- If you click "play twinkle with click" again, both sequences will play simultaneously in the same way as the first time (unless you click the stop button for the other sequence first).

Is it possible to implement players in such a way that they can play simultaneously? Otherwise I think possible solutions are:

- Whenever a player wants to start playing, it should first stop any other player (and call its `stop` callback).
- Prevent the player from starting if another player is playing.
- Advise users to not use more than one player at a time.

**Comment by notwaldorf** [comment]
> When the first player stops, the other one stops as well. However, only the callback for the first player gets called.
Yeah, this definitely looks like it's the case: [code](https://github.com/tensorflow/magenta-js/blob/master/music/src/core/player.ts#L206). When we call `stop()`, this also stops the tone.js Transport, which is going to also stop the other player.

I think the best solution for now is to document this (your option 3). Options 1 and 2 sound hard, because I don't know if we can tell from playerA that playerB also exists, so this sounds like a thing that should be checked on the app side, not the Player side. I really don't want to add a "PlayerManager" that keeps track of all the Players instantiated in the app and tries to manage them, so I think documenting this to cause less surprises is the best.

Would you like to send me a PR? 🙏

**Comment by cifkao** [comment]
Looking at the code, couldn't option 2 be implemented just by checking `Tone.Transport.state`, and throwing an exception if it's already playing? And analogously for stopping, pausing and resuming. That seems like a more reasonable behavior (if you click the wrong button, nothing is going to happen, as opposed to unexpected things happening). It would also fix the demo, I think.
