### ISSUE TITLE
continueSequence requires the progressive chords array whereas the doc says it's optional

### ISSUE THREAD

**Issue by Jars-of-jam-Scheduler** [magenta/magenta-js#461]
Hi everyone,

From https://magenta.github.io/magenta-js/music/classes/_music_rnn_model_.musicrnn.html#continuesequence we can see that `chordProgression` is optional.

In my code I have:

`let improvisedMelody = await music_rnn.continueSequence(quantizedSequence, 20, 0.5)`

Which results in this JS error:

    Uncaught (in promise) Error: Chord progression expected but not provided.
        at t.<anonymous> (music:83)
        at music:83
        at Object.next (music:83)
        at music:83
        at new Promise (<anonymous>)
        at r (music:83)
        at t.continueSequenceImpl (music:83)
        at t.<anonymous> (music:83)
        at music:83
        at Object.next (music:83)

However I can solve this error by adding this array:

    let improvisedMelody = await music_rnn.continueSequence(quantizedSequence, 20, 0.1, ['Bm'] )

So I think that the documentation is not up-to-date. Do you confirm this?

Furthermore, I don't know what to put in this array of progressive chords: in which way does this parameter influence the output of the improvised sequence? Is it really important?

Thank you,
Best regards,

**Comment by notwaldorf** [comment]
What checkpoint are you using? I think whether or not it’s optional depends
on how the model was trained.

**Comment by Jars-of-jam-Scheduler** [comment]
The checkpoint is: https://storage.googleapis.com/magentadata/js/checkpoints/music_rnn/chord_pitches_improv :-) .

**Comment by notwaldorf** [comment]
Right, so since `chord_pitches` is in the name, that means that parameter isn't optional (and it's an array of chord names) -- it will make sure that the generated notes follow the chord progression specified. Here's [some sample code](https://github.com/magenta/magenta-js/blob/master/music/demos/music_rnn.ts#L156) on how to use that parameter.

**Comment by Jars-of-jam-Scheduler** [comment]
Thank you. After all, it does make sense. However, for someone who doesn't know much about music theory like I do, you don't necessarily have the presence of mind to tell yourself that since the term "chord_pitches" is part of the checkpoint name, then the parameter isn't optional (even if it seems obvious afterwards). Perhaps the reader's attention should be drawn to this fact in the documentation (or not, idk)? :-)
Are there concrete examples of notes that follow this or that chord progression? This would allow me to have a more precise idea of what it is used for, as it remains unclear.

**Comment by notwaldorf** [comment]
Yeah, to your comment, I think we document the checkpoints fairly poorly. If you have any ideas on how we could do that better (other than the error we're throwing), I'd appreciate it.

I'm not sure what you mean by "concrete example of notes that follow this or that chord progression". A chord progression is something like C–G–Am–F, which is something that's super popular in pop music. When you provide a chord progression, the generated samples will try to follow those chords, but might not be _just_ those chords.

@iansimon, how would you explain this better? I feel i'm doing a bad job

**Comment by iansimon** [comment]
@notwaldorf Your explanation is great!

Unfortunately, a little bit of music theory knowledge is probably necessary to use a chord-conditioned model, because the model needs to be provided chord names like 'Bm' or 'C#7' that have strong implications about which notes will be played.

For the theory-averse, I would advise using basic_rnn or melody_rnn instead, though I'm not sure what text we could add to the doc to make that clearer.

**Comment by notwaldorf** [comment]
Closing this issue because I think we've addressed the original question. 🎉
