### ISSUE TITLE
How to select instrument in SoundFontPlayer class?

### ISSUE THREAD

**Issue by rignato** [magenta/magenta-js#508]
In the [player demo](https://magenta.github.io/magenta-js/music/demos/player.html), there is a dropdown for the `SoundFont` player that allows for selecting an instrument other than the Acoustic Grand Piano. Is there a way to do this when creating a `SoundFontPlayer` class?  

I've looked through the documentation and couldn't find anything pertaining to this, so I'd greatly appreciate any clarification.

**Comment by notwaldorf** [comment]
The instruments are picked automatically from the note sequence metadata (the note's program), rather than having a generic note sequence and telling it what to play it as. In that dropdown, every instrument corresponds to an integer (accoustic grand is 0, etc). Then, you can just set all your notes in the sequence to have that program (like we do [here](https://github.com/magenta/magenta-js/blob/master/music/demos/player.ts#L223))

**Comment by rignato** [comment]
Ah,  I see, thank you for the clarification!
