### ISSUE TITLE
Tone/Transfer Unsupported Output Device

### ISSUE THREAD

**Issue by Harmonybear** [magenta/magenta-js#511]
The sample rate of my audio interface is 44,100Hz but Tone/Transfer (https://sites.research.google/tonetransfer) tells me it isn't: "It looks like your output device has a sample rate of less than 44,100Hz. Please switch to an output device that supports at least 44,100Hz." I'm using Safari on a Mac. What gives? Thanks for any help!

**Comment by EdwinToh** [comment]
Hi @Harmonybear , if you launch "Audio MIDI Setup" on your mac, you will be able to check your output device's sample rate. We've noticed that if you're using bluetooth headsets, when the microphone is activated, the output sample rate goes to 16kHz. And since Safari doesn't allow any audiocontext to be created that is less than 44.1khz, tone transfer simply won't work on Safari. 

Having said that, Chrome and Firefox doesn't have this issue at all, so if you can, try Tone Transfer on either of these browsers.

**Comment by Harmonybear** [comment]
Thank you! I do appreciate the help! This is an awesome bit of AI!
